
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cl.bicevida.linea_credito_servicios.view.ws.servicios;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-14T09:36:15.684-03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "BV_SaldoLCR",
                      portName = "BV_SaldoLCRSoapHttpPort",
                      targetNamespace = "http://servicios.ws.view.linea_credito_servicios.bicevida.cl/",
                      wsdlLocation = "file:/C:/Sandbox/SVirtual/wspace10.4/bicevida-sucursalvirtual-rentasvitalicias-middleware/bv-rentasvitalicias-mid-fde/src/main/resources/wsdl/saldo.wsdl",
                      endpointInterface = "cl.bicevida.linea_credito_servicios.view.ws.servicios.BVSaldoLCR")
                      
public class BV_SaldoLCRSoapHttpPortImpl implements BVSaldoLCR {

    private static final Logger LOG = Logger.getLogger(BV_SaldoLCRSoapHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cl.bicevida.linea_credito_servicios.view.ws.servicios.BVSaldoLCR#saldoLCR(java.lang.String numeroCuenta)*
     */
    public cl.bicevida.linea_credito_servicios.view.ws.servicios.SaldoLineaCredito saldoLCR(java.lang.String numeroCuenta) { 
        LOG.info("Executing operation saldoLCR");
        System.out.print("numeroCuenta:");
        System.out.println(numeroCuenta);
        try {
            cl.bicevida.linea_credito_servicios.view.ws.servicios.SaldoLineaCredito _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
