package cl.bicevida.linea_credito_servicios.view.ws.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-14T09:36:15.761-03:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://servicios.ws.view.linea_credito_servicios.bicevida.cl/", name = "BV_SaldoLCR")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BVSaldoLCR {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://servicios.ws.view.linea_credito_servicios.bicevida.cl/", partName = "return")
    public SaldoLineaCredito saldoLCR(
        @WebParam(partName = "NumeroCuenta", name = "NumeroCuenta")
        java.lang.String numeroCuenta
    );
}
