
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oracle.xmlns.bv_consultasaldo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-21T18:05:25.955-03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "BV_ConsultaSaldo",
                      portName = "BV_ConsultaSaldoPort",
                      targetNamespace = "http://xmlns.oracle.com/BV_ConsultaSaldo",
                      wsdlLocation = "file:/C:/Sandbox/SVirtual/wspace10.4/bicevida-sucursalvirtual-rentasvitalicias-middleware/bv-rentasvitalicias-mid-credivida/src/main/resources/wsdl/consultasaldo.wsdl",
                      endpointInterface = "com.oracle.xmlns.bv_consultasaldo.BVConsultaSaldo")
                      
public class BV_ConsultaSaldoPortImpl implements BVConsultaSaldo {

    private static final Logger LOG = Logger.getLogger(BV_ConsultaSaldoPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oracle.xmlns.bv_consultasaldo.BVConsultaSaldo#process(cl.bicevida.consultasaldoin.MediosPagos payload)*
     */
    public cl.bicevida.consultasaldoout.MediosPagos process(cl.bicevida.consultasaldoin.MediosPagos payload) { 
        LOG.info("Executing operation process");
        System.out.println(payload);
        try {
            cl.bicevida.consultasaldoout.MediosPagos _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
