package com.oracle.xmlns.bv_consultasaldo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-21T18:05:26.008-03:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/BV_ConsultaSaldo", name = "BV_ConsultaSaldo")
@XmlSeeAlso({cl.bicevida.consultasaldoin.ObjectFactory.class, cl.bicevida.consultasaldoout.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BVConsultaSaldo {

    @WebMethod(action = "process")
    @WebResult(name = "MediosPagos", targetNamespace = "http://www.bicevida.cl/ConsultaSaldoOut", partName = "payload")
    public cl.bicevida.consultasaldoout.MediosPagos process(
        @WebParam(partName = "payload", name = "MediosPagos", targetNamespace = "http://www.bicevida.cl/ConsultaSaldoIn")
        cl.bicevida.consultasaldoin.MediosPagos payload
    );
}
