package com.oracle.xmlns.bv_estadotarjeta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-21T18:05:26.568-03:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/BV_EstadoTarjeta", name = "BV_EstadoTarjeta")
@XmlSeeAlso({cl.bicevida.estadotarjetaout.ObjectFactory.class, cl.bicevida.estadotarjetain.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BVEstadoTarjeta {

    @WebMethod(action = "process")
    @WebResult(name = "MediosPagos", targetNamespace = "http://www.bicevida.cl/EstadoTarjetaOut", partName = "payload")
    public cl.bicevida.estadotarjetaout.MediosPagos process(
        @WebParam(partName = "payload", name = "MediosPagos", targetNamespace = "http://www.bicevida.cl/EstadoTarjetaIn")
        cl.bicevida.estadotarjetain.MediosPagos payload
    );
}
