
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cl.bicevida.credivida.model.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-21T17:12:19.761-03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSCartolasCRV",
                      portName = "WSCartolasCRVSoapHttpPort",
                      targetNamespace = "http://ws.model.credivida.bicevida.cl/",
                      wsdlLocation = "file:/C:/Sandbox/SVirtual/wspace10.4/bicevida-sucursalvirtual-rentasvitalicias-middleware/bv-rentasvitalicias-mid-cartolas/src/main/resources/wsdl/cartola.wsdl",
                      endpointInterface = "cl.bicevida.credivida.model.ws.WSCartolasCRV")
                      
public class WSCartolasCRVSoapHttpPortImpl implements WSCartolasCRV {

    private static final Logger LOG = Logger.getLogger(WSCartolasCRVSoapHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cl.bicevida.credivida.model.ws.WSCartolasCRV#getCartolaUnificada(cl.bicevida.credivida.model.ws.types.GetCartolaUnificadaElement parameters)*
     */
    public cl.bicevida.credivida.model.ws.types.GetCartolaUnificadaResponseElement getCartolaUnificada(cl.bicevida.credivida.model.ws.types.GetCartolaUnificadaElement parameters) { 
        LOG.info("Executing operation getCartolaUnificada");
        System.out.println(parameters);
        try {
            cl.bicevida.credivida.model.ws.types.GetCartolaUnificadaResponseElement _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
